In progress...

diff --git a/git-store b/git-store
--- a/git-store
+++ b/git-store
@@ -302,7 +302,7 @@ _escape_ereg() {
 }
 
 git_store() {
-    git --git-dir="$STORE_GIT_DIR" $@
+    git --git-dir="$STORE_GIT_DIR" "$@"
 }
 
 _define_remote_store_name() {
@@ -387,22 +387,13 @@ store_add() {
         fi
         # Store the file
         local hash=$(git_store hash-object -t blob -w "$full") || exit $?
+        git_store update-ref "$REFS_STORE/$hash" $hash || exit $?
         local object="$STORE_OBJECTS_DIR/$hash"
         mv -f "$full" "$object" || exit 1
         chmod a-w "$object" || exit 1
         ln -sf $(relpath "$STORE_OBJECTS_DIR/$hash" "${full%/*}") "$full" || exit 1
         # Add the link
         git add "$file"
-        local old_hash=$(_get_hash_from_store "$full")
-        if [[ "$old_hash" != "$hash" ]]; then
-            local relfile=$(_get_relative_store_path_from_rootdir "$full")
-            if [[ -f "$STORE_INDEX" ]]; then
-                local ereg="$(_escape_ereg "$file")"
-                egrep -v "^[AD][|]${ereg}[|]" "$STORE_INDEX" > "$STORE_INDEX"~
-            fi
-            echo "A|$relfile|$hash" >> "$STORE_INDEX"~
-            mv "$STORE_INDEX"~ "$STORE_INDEX"
-        fi
     done
 }
 
@@ -446,10 +437,29 @@ _fetch_remote_ref() {
     local exit_code=$?
     case "$exit_code" in
         0) ;;
-        2) die "The reference doesn't exists on $REMOTE_STORE!\n" ;;
+        2) error "The reference doesn't exists on $REMOTE_STORE!\n"; return $exit_code ;;
         *) die "Can't get remote reference !\nIs the $REMOTE_STORE repository initialized correctly ?\n"
     esac
     git_store fetch -q $REMOTE_STORE_URL $REFS_STORE/$ref:$REFS_STORE/$ref 2>&1
+}
+
+_fetch_remote_ref_all_files() {
+    local ref='all_files'
+    _define_remote_store_name
+    # First check if the repository is correctly initialized and ref exists
+    git_store ls-remote --exit-code $REMOTE_STORE_URL $REFS_STORE/$ref >/dev/null
+    local exit_code=$?
+    case "$exit_code" in
+        0) git_store fetch -q $REMOTE_STORE_URL $REFS_STORE/$ref:$REFS_STORE/$ref 2>&1
+           ;;
+        2) # If the all_files reference doesn't exists on the remote create an empy one
+           local empty_blob_hash=$(git_store hash-object -w /dev/null)
+           git_store update-ref $REFS_STORE/$ref $empty_blob_hash
+           ;;
+        *) die "Can't get remote reference !\nIs the $REMOTE_STORE repository initialized correctly ?\n"
+           ;;
+    esac
+    return $?
 }
 
 store_commit() {
@@ -486,9 +496,10 @@ _do_checkout() {
         exit 1
     fi
 
-    local object_file=$(readlink -f "$full")
-    [[ "$object_file" != "$STORE_OBJECTS_DIR"/* ]] && exit 0
-    local hash=${object_file/$STORE_OBJECTS_DIR\/}
+    local object_file=$(readlink "$full")
+    [[ "$object_file" != *"$STORE_OBJECT_DIR_FROM_ROOT"/* ]] && return 0
+    local hash="${object_file##*/}" # get hash from object name
+    object_file="$STORE_OBJECTS_DIR/$hash" # fix bad link
     if [[ ! -f "$object_file" ]]; then
         # Check if the hash exists
         git_store cat-file -e $hash
@@ -498,12 +509,17 @@ _do_checkout() {
             _define_remote_store_name
             local relfile=$(_get_relative_store_path_from_rootdir "$full")
             printf "Downloading %s from %s...\n" "$(say_color cyan $relfile)" "$(say_color green $REMOTE_STORE)"
-            _fetch_remote_ref "$hash"
+            _fetch_remote_ref "$hash" || return $?
         fi
         git_store update-ref "$REFS_STORE/$hash" $hash
         git_store show $hash -- > "$object_file" || exit 1
     fi
     chmod a-w "$object_file"
+    if [[ ! -e "$full" ]]; then # fix bad link
+        local dirname_file="${full%/*}"
+        local object_file_relative_to_file=$(relpath "$object_file" "$dirname_file")
+        ln -sf "$object_file_relative_to_file" "$full" || exit $?
+    fi
 }
 
 store_checkout() {
@@ -511,12 +527,14 @@ store_checkout() {
     for arg in "${@}"; do
         [[ "$arg" == ':/' ]] && arg="$ROOT_DIR"
         if [[ -d "$arg" ]]; then
-            while read -r link_hash file; do
-                local object_file=$(git cat-file -p $link_hash)
-                if [[ "$ROOT_DIR/$object_file" == "$STORE_OBJECTS_DIR"/* ]]; then
-                    files_to_get+=( "$file" )
+            while read -r file; do
+                if [[ -L "$file" ]]; then
+                    local object_file=$(readlink "$file")
+                    if [[ "$object_file" == *"$STORE_OBJECT_DIR_FROM_ROOT"/* ]]; then
+                        files_to_get+=( "$file" )
+                    fi
                 fi
-            done < <(git ls-files -s "$arg"  | awk '/^120000/ { $1=$3=""; printf "%s\n",substr($0,2)}' )
+            done < <(git ls-files -c -o "$arg")
         else
             files_to_get+=( "$arg" )
         fi
@@ -534,7 +552,7 @@ store_list() {
     local cmd
     local tmp1
     if [[ "$OPT_REMOTE" -eq 1 ]]; then
-        _fetch_remote_ref 'all_files'
+        _fetch_remote_ref_all_files || exit $?
         cmd=("git_store" "show" "$REFS_STORE/all_files")
     else
         tmp1=$(mktemp)
@@ -682,7 +700,8 @@ store_push() {
         echo "git config remote.${REMOTE_STORE}.url USERNAME@HOST:/path/to/repository.git" >&2
         exit 1
     fi
-    _fetch_remote_ref 'all_files'
+
+    _fetch_remote_ref_all_files || exit $?
 
     git_store show $REFS_STORE/all_files -- | egrep -v '^#' > "$tmp1"
     cut -d'|' -f1-2 "$tmp1" | sort -u > "$tmp1".mini
@@ -728,50 +747,49 @@ store_push() {
 }
 
 store_cleanup() {
-    local tmp1=$(mktemp)
+    # Simple cleanup by removing data directory
+    rm -rf "$STORE_OBJECTS_DIR"
 
+    local tmp1=$(mktemp)
     git_store for-each-ref --format='%(objectname) %(objecttype) %(refname)' | \
-        sed -nr "s|^([A-Fa-f0-9]{40})\s+blob\s+$REFS_STORE/[A-Fa-f0-9]{40}$|\1|p" | sort -u >"$tmp1"
+     sed -nr "s|^([A-Fa-f0-9]{40})\s+blob\s+$REFS_STORE/[A-Fa-f0-9]{40}$|\1|p" | sort -u > "$tmp1"
 
     local tmp2=$(mktemp)
-    [[ -f "${STORE}" ]] && sed -nr "s|^([A-Fa-f0-9]{40})[|].*|\1|p" "${STORE}" | sort -u >"$tmp2"
+    while read -r link_hash file; do
+        local object_file=$(git cat-file -p $link_hash)
+        if [[ "$ROOT_DIR/$object_file" == "$STORE_OBJECTS_DIR"/* ]]; then
+            local hash="${object_file##*/}" # get hash from object name
+            echo "$hash" >> "$tmp2"
+        fi
+    done < <(git ls-files -s ":/"  | awk '/^120000/ { $1=$3=""; printf "%s\n",substr($0,2)}' )
 
-    local hash
+    sort -u "$tmp2" > "$tmp2".sort
+
     while read hash; do
         git_store update-ref -d "$REFS_STORE/$hash"
-    done < <(comm -2 -3 "$tmp1" "$tmp2")
+    done < <(comm -2 -3 "$tmp1" "$tmp2".sort)
 
-    [[ -f "${STORE}" ]] && sed -nr "s|^([A-Fa-f0-9]{40}[|][^|]+[|]).*|\1|p" "${STORE}" >"$tmp1"
-    git_store show $REFS_STORE/all_files 2>/dev/null | sed -nr "s|^([A-Fa-f0-9]{40}[|][^|]+[|]).*|\1|p" >"$tmp2"
-    local file
-    while read file; do
-        local full="$(_get_abspath_from_rootdir "$file")"
-        [[ ! -f "$full" ]] && continue
-        local local_hash=$(git_store hash-object "$full")
-        local ereg="$(_escape_ereg "$file")"
-        [[ $(egrep -c "^$local_hash[|]$ereg[|]" "$tmp1") -ne 0 ]] && continue
-        [[ $(egrep -c "^$local_hash[|]$ereg[|]" "$tmp2") -ne 0 ]] && rm -f "$full"
-    done < <( cut -d'|' -f2 "$tmp1" "$tmp2" | sort -u)
-
-    rm -f "$tmp1" "$tmp2"
+	# Prune all unreachable objects from the object database
+	git_store prune --expire now
+	
+    rm -f "$tmp1" "$tmp2" "$tmp2".sort
 }
 
 store_fix() {
-    local store_object_dir_from_root=$(_get_relative_store_path_from_rootdir "$STORE_OBJECTS_DIR")
-    while read -r link_hash file; do
+    while read -r file; do
         # The file must exists and the link must be wrong
         if [[ -L "$file" && ! -f "$file" ]]; then
-            local object_file=$(git cat-file -p $link_hash)
-            if [[ "$object_file" == *"$store_object_dir_from_root"/* ]]; then
+            local object_file=$(readlink "$file")
+            if [[ "$object_file" == *"$STORE_OBJECT_DIR_FROM_ROOT"/* ]]; then
                 local hash="${object_file##*/}" # get hash from object name
                 local object="$STORE_OBJECTS_DIR/$hash"
-                local dirname_file=$(_get_abspath_from_rootdir "$file")
+                local dirname_file=$(_get_abspath_from_pwd "$file")
                 dirname_file="${dirname_file%/*}"
                 local object_file_relative_to_file=$(relpath "$STORE_OBJECTS_DIR/$hash" "$dirname_file")
                 ln -sf "$object_file_relative_to_file" "$file" || exit $?
             fi
         fi
-    done < <(git ls-files -s ":/"  | awk '/^120000/ { $1=$3=""; printf "%s\n",substr($0,2)}' )
+    done < <(git ls-files -c -o ":/")
 }
 
 store_precommit() {
@@ -931,6 +949,7 @@ STORE_GIT_DIR="${git_dir}/store"
 STORE_INDEX="$STORE_GIT_DIR/store.idx"
 declare -r STORE_OBJECTS_DIR="${STORE_GIT_DIR}/data"
 [[ ! -d "$STORE_OBJECTS_DIR" ]] && mkdir -p "$STORE_OBJECTS_DIR"
+declare -r STORE_OBJECT_DIR_FROM_ROOT=$(_get_relative_store_path_from_rootdir "$STORE_OBJECTS_DIR")
 
 precommit_hook_script="$git_dir/hooks/pre-commit"
 if [[ ! -x "$precommit_hook_script" ]]; then
@@ -961,7 +980,7 @@ case "$ACTION" in
            printf "You must specified an action !" >&2
        else
            if [[ "${GIT_STORE_DEVELOPER:-0}" -eq 1 ]]; then
-               git_store "$ACTION" ${ARGS[@]:-}
+               git_store "$ACTION" "${ARGS[@]:-}"
                exit $?
            fi
            printf "Invalid action '$ACTION' !" >&2
